version: "3"


services:
  dj-server:
    build: .
    container_name: "mini-hackathon-weather-dj-server"
    env_file:
      - ./app/.env
    command:
      - sh
      - -c
      - |
        poetry run python manage.py migrate
        poetry run gunicorn --bind 0.0.0.0:8000 configs.wsgi:application
    volumes:
      - ./app:/app

  nginx:
    image: nginx:1.21-alpine
    container_name: "mini-hackathon-weather-nginx"
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dj-server
