# Generated by Django 5.0.7 on 2024-07-15 00:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", models.CharField(max_length=1024)),
                ("city", models.CharField(max_length=1024)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("city", "country")},
            },
        ),
        migrations.CreateModel(
            name="LocationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=30)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("timezone", models.CharField(max_length=1024)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_details",
                        to="Trip.location",
                    ),
                ),
            ],
            options={
                "unique_together": {("latitude", "longitude", "zip_code")},
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("preferences", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="Trip.locationdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripAdvise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("advise", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(choices=[("1", "Activity"), ("2", "Tip")], max_length=20),
                ),
                ("for_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "Pending"), ("2", "Completed"), ("3", "Failed")],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("timestamp_updated", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advises",
                        to="Trip.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "wmo_weather_code",
                    models.CharField(
                        choices=[
                            ("0", "Clear"),
                            ("1", "Mainly clear"),
                            ("2", "Partly cloudy"),
                            ("3", "Cloudy"),
                            ("45", "Fog"),
                            ("48", "Rime Fog"),
                            ("51", "Light Drizzle"),
                            ("53", "Drizzle"),
                            ("55", "Heavy Drizzle"),
                            ("56", "Light Freezing Drizzle"),
                            ("57", "Freezing Drizzle"),
                            ("61", "Light Rain"),
                            ("63", "Rain"),
                            ("65", "Heavy Rain"),
                            ("66", "Light Freezing Rain"),
                            ("67", "Freezing Rain"),
                            ("71", "Light Snow"),
                            ("73", "Snow"),
                            ("75", "Heavy Snow"),
                            ("77", "Snow Grains"),
                            ("80", "Light Showers"),
                            ("81", "Showers"),
                            ("82", "Heavy Showers"),
                            ("85", "Light Snow Showers"),
                            ("86", "Snow Showers"),
                            ("95", "Thunderstorm"),
                            ("96", "Light Thunderstorms With Hail"),
                            ("99", "Thunderstorm With Hail"),
                        ],
                        max_length=3,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_series",
                        to="Trip.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "dt")},
            },
        ),
    ]
